config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'home', to: 'main#home', as: :home
  get 'profile', to: 'profiles#my', as: :my_profile
  get 'profile/:id', to: 'profiles#show', as: :profile
  patch 'profile/:id', to: 'profiles#update'
  put 'profile/:id', to: 'profiles#update'
  get 'profile/:id/edit', to: 'profiles#edit', as: :edit_profile

  patch 'lists/add_user', to: 'lists#add_user', as: :add_user
  patch 'lists/:list_id/remove_user/:user_id', to: 'lists#remove_user', as: :remove_user

  patch 'comment', to: 'comments#comment', as: :user_comment

  get 'headhunt', to: 'main#headhunt', as: :headhunt
  post 'headhunt', to: 'main#headhunted', as: :headhunted

  devise_for :users, controllers: { registrations: 'registrations'}

  root 'main#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  extend Enumerize

  belongs_to :user
  has_one :address, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :address
  has_many :images, -> { order(position: :asc) }, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: lambda { |i| i[:id].nil? && i[:file].blank? && i[:file_cache].blank? }, allow_destroy: true

  has_many :videos, -> { order(position: :asc) }, as: :videoable, dependent: :destroy
  accepts_nested_attributes_for :videos, reject_if: lambda { |i| i[:url].blank? }, allow_destroy: true

  serialize :job_type, Array
  serialize :ethnicity, Array
  serialize :available_for, Array

  serialize :language, Array

  enumerize :job_type, in: [:cast, :crew], multiple: true
  enumerize :gender, in: [:male, :female]
  enumerize :ethnicity, in: [:african, :asian, :eastern_european, :indian, :latin_american, :mediterraenan, :middle_eastern, :native_american, :north_african, :scandinavian, :white], multiple: true
  enumerize :eye_color, in: [:light_blue, :bright_blue, :dark_brown, :light_brown, :green, :gray, :mixed]
  enumerize :hair_color, in: [:black, :very_dark_brown, :brown, :light_brown, :dark_blonde, :light_blonde, :platinum_blonde, :ginger, :red, :other]
  enumerize :hair_length, in: [:bald, :very_short, :short, :medium, :long, :very_long]
  enumerize :hair_type, in: [:straight, :curly, :wavy, :kinky]
  enumerize :employment, in: [:student, :employee, :self_employed, :retired, :unemployed]
  enumerize :available_for, in: [:swimwear, :underwear, :unrecognizable_nude, :artistic_nude, :bodypaint], multiple: true

  enumerate :clothing_size, with: ClothingSize


  validates :job_type, presence: true
  validate do
    errors.add(:job_type, 'can\'t be blank') if job_type.empty?
  end
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :phone_number, format: /\+[0-9]{8,}/
  validates :birthday, presence: true
  validates :birthday, date: { before: Proc.new { Date.today }, message: 'must be before today' }
  validates :gender, presence: true
  validates :nationality, presence: true
  validates :ethnicity, presence: true
  validate do
    errors.add(:ethnicity, 'can\'t be blank') if ethnicity.empty?
  end
  validates :language, presence: true
  validate do
    errors.add(:language, 'can\'t be blank') if language.empty?
  end

  with_options if: 'job_type.cast?' do |cast|
    cast.validates :height, presence: true
    cast.validates :height, numericality: { greater_than: 0, less_than_or_equal_to: 240 }
    cast.validates :weight, presence: true
    cast.validates :weight, numericality: { greater_than: 0 }
    cast.validates :shoe_size, presence: true
    cast.validates :shoe_size, numericality: { greater_than: 0, less_than_or_equal_to: 50 }
    cast.validates :clothing_size, presence: true
    cast.validates :eye_color, presence: true
    cast.validates :hair_color, presence: true
    cast.validates :hair_length, presence: true
    cast.validates :hair_type, presence: true
  end

  with_options if: 'job_type.crew?' do |crew|
  end

  validates :employment, presence: true

  validate do
    if images.select {|d| !d.marked_for_destruction? }.count < 2
      errors.add(:images, 'missing (add at least 2)')
    end
  end

  validates_associated :address

  after_initialize :init_address, :if => :new_record?

  def init_address
    build_address if address.nil?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  has_one :profile, dependent: :destroy

  has_and_belongs_to_many :lists
  # has_and_belongs_to_many :events

  has_one :comment, dependent: :destroy

  accepts_nested_attributes_for :profile

  after_initialize :init_profile, :if => :new_record?

  has_and_belongs_to_many :talents

  validates :terms_and_conditions, acceptance: true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where.not(active: true) }
  scope :admin, -> { active.where(admin: true) }
  scope :cast, -> { active.where.not(admin: true).joins(:profile).where("profiles.job_type LIKE ?", '%cast%') }
  scope :crew, -> { active.where.not(admin: true).joins(:profile).where("profiles.job_type LIKE ?", '%crew%') }

  scope :talent_eq, -> (talent=1) { joins(:talents).where(talents: {id: Talent.find(talent).subtree_ids}).distinct }

  scope :full_name, -> (name) { joins(:profile).where("#{SQLHelper.db_concat(:first_name, ' ', :last_name)} LIKE ?", "%#{name}%") }

  scope :profile_age_gteq, -> (age=1) { joins(:profile).where("profiles.birthday <= ?", age.to_i.years.ago )}
  scope :profile_age_lteq, -> (age=1) { joins(:profile).where("profiles.birthday >= ?", (age.to_i+1).years.ago + 1.day )}

  scope :city, -> (city) { joins(profile: :address).where("addresses.city LIKE ?", "%#{city}%")}

  def init_profile
    build_profile if profile.nil?
  end

  def full_name
    profile.nil? ? email : "#{profile.first_name} #{profile.last_name}"
  end

  def cast?
    profile.job_type.include? "cast"
  end

  def crew?
    profile.job_type.include? "crew"
  end

  def active_for_authentication?
    super and self.active?
  end

  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    result = update_attributes(params)
    clean_up_passwords
    return result
  end

  private

  def self.ransackable_scopes(auth_object=nil)
    %i(talent_eq full_name profile_age_gteq profile_age_lteq city)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def my
    @user = current_user
    @lists = @user ? @user.lists : []
    if @user && can?(:read, @user)
      @comment = Comment.where(user_id: @user.id).first_or_initialize
      if !@user.profile.valid?
        flash.now[:alert] = invalid_profile_warning @user
      end
      render "show"
    else
      flash[:error] = I18n.t(:permission_denied)
      redirect_to home_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @lists = @user ? @user.lists : []
    if @user && can?(:read, @user)
      @comment = Comment.where(user_id: @user.id).first_or_initialize
    else
      flash[:error] = I18n.t(:permission_denied)
      redirect_to home_path
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user && can?(:update, @user)
      render locals: { resource: @user }
    else
      flash[:error] = I18n.t(:permission_denied)
      redirect_to home_path
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user && can?(:update, @user)
      set_positions params[:user][:profile_attributes][:images_attributes]
      set_positions params[:user][:profile_attributes][:videos_attributes]
      if @user.update_attributes user_parameters
        redirect_to profile_path(@user), notice: 'User has been updated successfully.'
      else
        flash.now[:error] = model_errors @user
        render 'edit', locals: { resource: @user }
      end
    else
      flash[:error] = I18n.t(:permission_denied)
      redirect_to home_path
    end
  end

  protected

  def set_positions items
    items.each_with_index do |item, index|
      key, value = item
      value['position'] = index + 1
    end if items
  end

  private
  def user_parameters
    params.require(:user).permit(:email, :active, :admin, {:talent_ids => []}, profile_attributes: [
      :id,
      { :job_type => [] },
      :first_name,
      :last_name,
      :phone_number,
      :birthday,
      :gender,
      :nationality,
      { :ethnicity => [] },
      { :language => [] },
      :height,
      :weight,
      :shoe_size,
      :clothing_size,
      :eye_color,
      :hair_color,
      :hair_length,
      :hair_type,
      :haircut,
      :beard,
      :mustache,
      :tattoos,
      :piercings,
      :employment,
      :driving_license,
      :own_transport,
      { :available_for => [] },
      :previous_experience,
      address_attributes: [
        :id,
        :street,
        :number,
        :bus,
        :city,
        :country,
        :postal_code
      ],
      images_attributes: [:id, :file, :file_cache, :position, :_destroy],
      videos_attributes: [:id, :title, :url, :position, :_destroy]
      ])
  end

  def invalid_profile_warning user
    warning = "<h4>#{I18n.t(:invalid_profile)}</h4>"
    warning += "<ul>" + user.profile.errors.full_messages.map { |msg| "<li>#{msg}</li>" }.join('') + "</ul>"
    warning += "<p><br /><a href='#{edit_profile_path(user)}' class='alert-link'>#{I18n.t(:edit_profile)}</a></p>"
    return warning.html_safe
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_image_fields.html.erb
<li class="nested-fields">
  <div class="input-group">
    <span class="input-group-addon light">
      <%= icon(:move) %>
    </span>
    <% if f.object.file? %>
      <%= image_tag(f.object.file.url(:tiny_thumb)) %>
    <% else %>
      <%= f.input :file, label: false %>
    <% end %>
    <%= f.input :file_cache, as: :hidden %>
    <%= f.input :id, as: :hidden %>
    <span class="input-group-addon light">
      <%= link_to_remove_association(icon('minus-sign', 'text-danger'), f) %>
    </span>
  </div>
</li>

app/views/profiles/_profile_fields.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Looking for work as</h3>
  </div>
  <div class="panel-body">
    <%= f.input :job_type, as: :check_boxes, label: false %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Contact information</h3>
  </div>
  <div class="panel-body">

    <div class="row">
      <div class="col-sm-6">
        <%= f.input :first_name %>
      </div>
      <div class="col-sm-6">
        <%= f.input :last_name %>
      </div>
    </div>

    <hr />

    <%= f.semantic_fields_for :address do |af| %>
      <div class="row">
        <div class="col-md-6">
          <%= af.input :street %>
        </div>
        <div class="col-md-3 col-xs-6">
          <%= af.input :number %>
        </div>
        <div class="col-md-3 col-xs-6">
          <%= af.input :bus %>
        </div>
      </div>
      <div class="row">

        <div class="col-md-6">
          <%= af.input :city %>
        </div>
        <div class="col-md-3 col-sm-6">
          <%= af.input :postal_code %>
        </div>
        <div class="col-md-3 col-sm-6">
          <%= af.input :country, :priority_countries => ["BE"] %>
        </div>
      </div>

    <% end %>

    <hr />

    <%= f.input :phone_number, hint: 'use format +32485123456' %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Personal information</h3>
  </div>
  <div class="panel-body">

    <%= f.input :birthday, as: :string, input_html: { data: { provide: :datepicker, date_format: 'dd/mm/yyyy' } }  %>
    <%= f.input :gender, as: :radio %>
    <%= f.input :nationality, as: :country, :priority_countries => ["BE"] %>
    <%= f.input :ethnicity, as: :check_boxes %>
    <%= f.input :language, label: t(:languages), as: :select, multiple: true, collection: LanguageList::COMMON_LANGUAGES.map{|l|[l.name, l.iso_639_1]}  %>
  </div>
</div>

<div class="show-cast">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Physical characteristics</h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-6">
          <%= f.input :height, append: ' cm' %>
        </div>
        <div class="col-xs-6">
          <%= f.input :weight, append: ' kg' %>
        </div>
      </div>
      <%= f.input :shoe_size %>
      <div class="show-female show-adult clear-hidden">
        <%= f.input :clothing_size, as: :select, include_blank: false, collection: ClothingSize.to_select(:female) %>
      </div>
      <div class="show-male show-adult clear-hidden">
        <%= f.input :clothing_size, as: :select, include_blank: false, collection: ClothingSize.to_select(:male) %>
      </div>
      <div class="show-child clear-hidden">
        <%= f.input :clothing_size, as: :select, include_blank: false, collection: ClothingSize.to_select(:child) %>
      </div>
      <%= f.input :eye_color, as: :select, include_blank: false %>
      <%= f.input :hair_color, as: :select, include_blank: false %>
      <%= f.input :hair_length, as: :select, include_blank: false %>
      <%= f.input :hair_type, as: :select, include_blank: false %>

      <%= f.input :haircut %>
      <%= f.input :beard, wrapper_html: { class: 'show-male clear-hidden' } %>
      <%= f.input :mustache, wrapper_html: { class: 'show-male clear-hidden' } %>
      <%= f.input :tattoos %>
      <%= f.input :piercings %>
    </div>
  </div>

</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Additional information</h3>
  </div>
  <div class="panel-body">
    <%= f.input :employment, as: :select, include_blank: false %>
    <%= f.input :driving_license %>
    <%= f.input :own_transport %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Talent</h3>
  </div>
  <div class="panel-body">

    <div class="show-cast clear-hidden">
      <h4><%= t(:cast) %></h4>
      <hr />
      <%= nested_talent_options user, Talent.friendly.find('cast').children, Talent.friendly.find('cast') %>
      <hr />
      <%= f.input :available_for, as: :check_boxes %>
      <hr />
    </div>

    <div class="show-crew clear-hidden">
      <h4><%= t(:crew) %></h4>
      <hr />
      <%= nested_talent_options user, Talent.friendly.find('crew').children, Talent.friendly.find('crew') %>
      <hr />
    </div>

    <%= f.input :previous_experience, :input_html => { rows: 5 } %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Media</h3>
  </div>
  <div class="panel-body">
    <h3>Images</h3>
    <p class="help-block">Add at least 2 recent photos: a clear picture of the face and one of the person completely</p>
    <ul id="sortable-images" class="sortable-fields list-unstyled clearfix">
      <%= f.semantic_fields_for :images do |image| %>
        <%= render partial: 'profiles/image_fields', locals: {f: image} %>
      <% end %>

      <div class="add-image">
        <%= link_to_add_association icon(:plus) + " " + t(:add_image), f, :images, partial: 'profiles/image_fields', class: 'btn btn-link' %>
      </div>
    </ul>
    <h3>Videos</h3>
    <ul id="sortable-videos" class="sortable-fields list-unstyled clearfix">
      <%= f.semantic_fields_for :videos do |video| %>
        <%= render partial: 'profiles/video_fields', locals: {f: video} %>
      <% end %>
      <div class="add-video">
        <%= link_to_add_association icon(:plus) + " " + t(:add_video), f, :videos, partial: 'profiles/video_fields', class: 'btn btn-link' %>
      </div>
    </ul>
  </div>
</div>

app/views/profiles/_video_fields.html.erb
<li class="nested-fields">
  <div class="input-group">
    <span class="input-group-addon light">
      <%= icon(:move) %>
    </span>
    <div class="row">
      <div class="col-sm-8"><%= f.input :url, label: false, placeholder: t(:link)  %></div>
      <div class="col-sm-4"><%= f.input :title, label: false, placeholder: t(:description)  %></div>
    </div>
    <%= f.input :id, as: :hidden %>
    <span class="input-group-addon light">
      <%= link_to_remove_association(icon('minus-sign', 'text-danger'), f) %>
    </span>
  </div>
</li>

app/views/profiles/edit.html.erb
<% provide :title, t(:edit_user_profile) %>

<div class="row">
  <div class="col-sm-12">
    <%= semantic_form_for(resource, url: profile_path(resource), html: { multipart: true, method: :put }) do |f| %>

      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Account information</h3>
        </div>
        <div class="panel-body">
          <%= f.input :email %>
          <% if Devise.mappings[:user].confirmable? && resource.pending_reconfirmation? %>
            <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
          <% end %>

          <%= f.input :active %>

        </div>
      </div>

      <%= f.semantic_fields_for :profile do |pf| %>
        <%= render partial: 'profile_fields', locals: {user: resource, f: pf} %>
      <% end %>


        <div class="actions">
          <%= f.submit "Update profile", class: 'btn btn-primary btn-block' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<% provide :title, @user.full_name %>

<div class="row">
  <div class="col-sm-8 col-md-6">
    <div class="well user-details">
      <dl class="dl-horizontal">
        <h3>Contact information</h3>

        <dt><%= t(:name) %></dt>
        <dd><%= @user.full_name %></dd>

        <dt><%= t(:email) %></dt>
        <dd><%= mail_to @user.email, @user.email %></dd>

        <dt><%= t(:address) %></dt>
        <dd><%= simple_format @user.profile.address.to_s, {}, wrapper_tag: :div %></dd>

        <dt><%= t(:phone_number) %></dt>
        <dd><%= link_to @user.profile.phone_number, "tel:#{@user.profile.phone_number}" %></dd>

        <hr />

        <h3>Personal information</h3>

        <dt><%= t(:birthday) %></dt>
        <dd><%= @user.profile.birthday ? l(@user.profile.birthday, format: :long) : t(:not_specified) %></dd>

        <dt><%= t(:gender) %></dt>
        <dd><%= @user.profile.gender ? @user.profile.gender.humanize : t(:not_specified) %></dd>

        <dt><%= t(:nationality) %></dt>
        <dd><%= @user.profile.nationality ? country_name(@user.profile.nationality) : t(:not_specified) %></dd>

        <dt><%= t(:ethnicity) %></dt>
        <dd><%= @user.profile.ethnicity.map { |e| e.text }.join(', ') %></dd>

        <dt><%= t(:language) %></dt>
        <dd><%= @user.profile.language.reject{|i|i.blank?}.map{|l| info = LanguageList::LanguageInfo.find(l); info ? info.name : nil}.compact.join(', ') %></dd>

        <hr />

        <% if @user.cast? %>

          <h3>Physical characteristics</h3>

          <dt><%= t(:height) %></dt>
          <dd><%= @user.profile.height ? "#{@user.profile.height/100}m#{@user.profile.height%100}" : t(:not_specified) %></dd>

          <dt><%= t(:weight) %></dt>
          <dd><%= @user.profile.weight ? "#{@user.profile.weight}kg" : t(:not_specified) %></dd>

          <dt><%= t(:shoe_size) %></dt>
          <dd><%= @user.profile.shoe_size ? @user.profile.shoe_size : t(:not_specified) %></dd>

          <dt><%= t(:clothing_size) %></dt>
          <dd><%= @user.profile.clothing_size ? ClothingSize[@user.profile.clothing_size.to_i] : t(:not_specified) %></dd>

          <dt><%= t(:eye_color) %></dt>
          <dd><%= @user.profile.eye_color ? @user.profile.eye_color.text : t(:not_specified) %></dd>

          <dt><%= t(:hair_color) %></dt>
          <dd><%= @user.profile.hair_color ? @user.profile.hair_color.text : t(:not_specified) %></dd>

          <dt><%= t(:hair_length) %></dt>
          <dd><%= @user.profile.hair_length ? @user.profile.hair_length.text : t(:not_specified) %></dd>

          <dt><%= t(:hair_type) %></dt>
          <dd><%= @user.profile.hair_type ? @user.profile.hair_type.text : t(:not_specified) %></dd>

          <dt><%= t(:haircut) %></dt>
          <dd><%= @user.profile.haircut ? t(:yes) : t(:no) %></dd>

          <% if @user.profile.gender.male? %>
            <dt><%= t(:beard) %></dt>
            <dd><%= @user.profile.beard ? t(:yes) : t(:no) %></dd>

            <dt><%= t(:mustache) %></dt>
            <dd><%= @user.profile.mustache ? t(:yes) : t(:no) %></dd>
          <% end %>

          <dt><%= t(:tattoos) %></dt>
          <dd><%= @user.profile.tattoos ? t(:yes) : t(:no) %></dd>

          <dt><%= t(:piercings) %></dt>
          <dd><%= @user.profile.piercings ? t(:yes) : t(:no) %></dd>

          <hr />

        <% end %>

        <h3>Additional information</h3>

        <dt><%= t(:employment) %></dt>
        <dd><%= @user.profile.employment ? @user.profile.employment.text : t(:not_specified) %></dd>

        <dt><%= t(:driving_license) %></dt>
        <dd><%= @user.profile.driving_license ? t(:yes) : t(:no) %></dd>

        <dt><%= t(:own_transport) %></dt>
        <dd><%= @user.profile.own_transport ? t(:yes) : t(:no) %></dd>

        <hr />

        <h3>Talent</h3>

        <% if @user.cast? %>
          <dt><%= t(:cast) %></dt>
          <dd><%= simple_format @user.talents.where(id: Talent.friendly.find('cast').subtree_ids).map{|t| t.to_s }.join("\n"), {}, wrapper_tag: :div %></dd>

          <% if @user.profile.available_for.present? %>
            <dt><%= t(:available_for) %></dt>
            <dd><%= simple_format @user.profile.available_for.map { |e| e.text }.join("\n"), {}, wrapper_tag: :div %></dd>
          <% end %>
        <% end %>

        <% if @user.crew? %>
          <dt><%= t(:crew) %></dt>
          <dd><%= simple_format @user.talents.where(id: Talent.friendly.find('crew').subtree_ids).map{|t| t.to_s }.join("\n"), {}, wrapper_tag: :div %></dd>
        <% end %>


        <% if @user.profile.previous_experience.present? %>
          <dt><%= t(:previous_experience) %></dt>
          <dd><%= simple_format @user.profile.previous_experience, {}, wrapper_tag: :div %></dd>
        <% end %>

      </dl>

    </div>

    <% if current_user %>
      <% if current_user.admin? %>
        <%= link_to t(:edit_user_profile), edit_profile_path(@user), class: 'btn btn-block btn-info hidden-print' %>
      <% elsif current_user == @user %>
        <%= link_to t(:update_your_profile), edit_user_registration_path, class: 'btn btn-block btn-info hidden-print' %>
      <% end %>
      <br />
      <% if current_user.admin? %>
        <div class="well user-lists">
          <dl class="dl-horizontal">
            <h3>Lists</h3>
            <% if @lists.empty? %>
              <em>empty</em>
            <% else %>
              <% @lists.each do |list| %>
                <dt><%= list.title %></dt>
                <dd><%= link_to t(:remove_from_list), remove_user_path(list, @user), method: :patch %></dd>
              <% end %>
            <% end %>
          </dl>
          <hr />
          <h3><%= t(:add_to_list) %></h3>
          <%= form_tag add_user_path, method: :patch do %>
            <%= hidden_field_tag :user_id, @user.id %>
            <div class="row">
              <div class="col-sm-8">
                <%= select_tag :list_id, options_for_select(List.where.not(id: @user.list_ids).map { |l| [l.title, l.id] }), class: 'form-control' %>
              </div>
              <div class="col-sm-4">
                <%= submit_tag "Add to list", class: 'btn btn-primary btn-block' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="well user-comment clearfix">
          <h3><%= t(:comments) %></h3>
          <%= form_tag user_comment_path, method: :patch do %>
            <%= hidden_field_tag :user_id, @user.id %>
            <%= text_area_tag :comment, @comment.text, cols: 40, rows: 10, class: 'form-control' %>
            <br />
            <%= submit_tag "Update comment", class: 'btn btn-primary btn-block' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-sm-4 col-md-6">
    <div class="image-container clearfix">
      <% @user.profile.images.each_with_index do |image, index| %>
        <% if index.zero? %>
        <div class="image media-element">
          <%= link_to image_tag(image.file.url, class: 'img-responsive'), image.file.url, rel: 'media', class: 'colorbox' %>
        </div>
        <% else %>
          <div class="image thumb media-element">
            <%= link_to image_tag(image.file.thumb.url, class: 'img-responsive'), image.file.url, rel: 'media', class: 'colorbox' %>
          </div>
        <% end %>
      <% end %>
    </div>
    <% if @user.profile.videos.present? %>
      <div class="video-container clearfix">
        <h3><%= t(:videos) %></h3>
        <% @user.profile.videos.each do |video| %>
          <div class="video media-element">
            <% if video.title.present? %>
              <p><%= video.title %></p>
            <% end %>
            <%= video.embed_code('responsive-embed hidden-print').html_safe %>
            <div class="visible-print-block">
              <%= link_to video.url, video.url %>
            </div>
            <hr />
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>